namespace CuoiKyWinForms;

public partial class MainForm
{
    private System.ComponentModel.IContainer components = new System.ComponentModel.Container();
    private SplitContainer mainSplit = null!;
    private Panel menuPanel = null!;
    private Panel contentPanel = null!;
    private Panel connectionView = null!;
    private Label menuTitle = null!;
    private Label connectionHeading = null!;
    private Label mathHeading = null!;
    private Label libraryHeading = null!;
    private Label projectHeading = null!;
    private Label serverLabel = null!;
    private TextBox serverText = null!;
    private Button testConnection = null!;
    private Label connectionStatus = null!;
    private Button navConnection = null!;
    private Button nav1 = null!;
    private Button nav2 = null!;
    private Button nav4 = null!;
    private Button nav3 = null!;
    private Button nav5 = null!;
    private Button nav6 = null!;
    private Button nav7 = null!;
    private Button nav8 = null!;
    private Panel calculationCard = null!;
    private Label calculationTitle = null!;
    private Label calculationDescription = null!;
    private Label calculationStatus = null!;
    private Button calculationButton = null!;
    private Panel libraryCard = null!;
    private Label libraryTitle = null!;
    private Label libraryDescription = null!;
    private Label libraryStatus = null!;
    private Button libraryButton = null!;
    private Panel projectCard = null!;
    private Label projectTitle = null!;
    private Label projectDescription = null!;
    private Label projectStatus = null!;
    private Button projectButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        mainSplit = new SplitContainer();
        menuPanel = new Panel();
        contentPanel = new Panel();
        connectionView = new Panel();
        menuTitle = new Label();
        connectionHeading = new Label();
        mathHeading = new Label();
        libraryHeading = new Label();
        projectHeading = new Label();
        serverLabel = new Label();
        serverText = new TextBox();
        testConnection = new Button();
        connectionStatus = new Label();
        navConnection = new Button();
        nav1 = new Button();
        nav2 = new Button();
        nav4 = new Button();
        nav3 = new Button();
        nav5 = new Button();
        nav6 = new Button();
        nav7 = new Button();
        nav8 = new Button();
        calculationCard = new Panel();
        calculationTitle = new Label();
        calculationDescription = new Label();
        calculationStatus = new Label();
        calculationButton = new Button();
        libraryCard = new Panel();
        libraryTitle = new Label();
        libraryDescription = new Label();
        libraryStatus = new Label();
        libraryButton = new Button();
        projectCard = new Panel();
        projectTitle = new Label();
        projectDescription = new Label();
        projectStatus = new Label();
        projectButton = new Button();
        ((System.ComponentModel.ISupportInitialize)mainSplit).BeginInit();
        mainSplit.Panel1.SuspendLayout();
        mainSplit.Panel2.SuspendLayout();
        mainSplit.SuspendLayout();
        menuPanel.SuspendLayout();
        contentPanel.SuspendLayout();
        connectionView.SuspendLayout();
        SuspendLayout();

        mainSplit.Dock = DockStyle.Fill;
        mainSplit.Size = new Size(1200, 760);
        mainSplit.FixedPanel = FixedPanel.Panel1;
        mainSplit.IsSplitterFixed = true;
        mainSplit.Panel1MinSize = 380;
        mainSplit.Panel2MinSize = 700;
        mainSplit.SplitterDistance = 400;
        mainSplit.Name = "mainSplit";
        mainSplit.Panel1.Controls.Add(menuPanel);
        mainSplit.Panel2.Controls.Add(contentPanel);
        menuPanel.Dock = DockStyle.Fill;
        menuPanel.Size = new Size(400, 760);
        menuPanel.AutoScroll = true;
        menuPanel.BackColor = Color.FromArgb(248, 250, 253);
        menuPanel.Name = "menuPanel";
        contentPanel.Dock = DockStyle.Fill;
        contentPanel.Size = new Size(796, 760);
        contentPanel.Name = "contentPanel";
        contentPanel.Controls.Add(connectionView);
        connectionView.Dock = DockStyle.Fill;
        connectionView.Size = new Size(796, 760);
        connectionView.BackColor = Color.White;
        connectionView.Name = "connectionView";
        connectionView.AutoScroll = true;

        menuTitle.Name = "menuTitle";
        menuTitle.Text = "Bài tập lớn SQL DBMS";
        menuTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        menuTitle.ForeColor = Color.FromArgb(29, 63, 111);
        menuTitle.Location = new Point(22, 20);
        menuTitle.Size = new Size(360, 42);
        connectionHeading.Name = "connectionHeading";
        connectionHeading.Text = "KẾT NỐI";
        connectionHeading.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        connectionHeading.ForeColor = Color.FromArgb(29, 63, 111);
        connectionHeading.Location = new Point(22, 82);
        connectionHeading.Size = new Size(360, 32);
        mathHeading.Name = "mathHeading";
        mathHeading.Text = "TOÁN HỌC";
        mathHeading.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        mathHeading.ForeColor = Color.FromArgb(29, 63, 111);
        mathHeading.Location = new Point(22, 192);
        mathHeading.Size = new Size(360, 32);
        libraryHeading.Name = "libraryHeading";
        libraryHeading.Text = "THƯ VIỆN";
        libraryHeading.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        libraryHeading.ForeColor = Color.FromArgb(29, 63, 111);
        libraryHeading.Location = new Point(22, 422);
        libraryHeading.Size = new Size(360, 32);
        projectHeading.Name = "projectHeading";
        projectHeading.Text = "CÔNG TY / ĐỀ ÁN";
        projectHeading.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        projectHeading.ForeColor = Color.FromArgb(29, 63, 111);
        projectHeading.Location = new Point(22, 652);
        projectHeading.Size = new Size(360, 32);
        navConnection.Name = "navConnection";
        navConnection.Text = "Kết nối";
        navConnection.Location = new Point(20, 120);
        navConnection.Size = new Size(360, 46);
        navConnection.BackColor = Color.White;
        navConnection.FlatStyle = FlatStyle.Flat;
        navConnection.TextAlign = ContentAlignment.MiddleLeft;
        navConnection.Click += navConnection_Click;
        nav1.Name = "nav1";
        nav1.Text = "Bài 1 — Phương trình bậc 1";
        nav1.Location = new Point(20, 232);
        nav1.Size = new Size(360, 46);
        nav1.BackColor = Color.White;
        nav1.FlatStyle = FlatStyle.Flat;
        nav1.TextAlign = ContentAlignment.MiddleLeft;
        nav1.Click += nav1_Click;
        nav2.Name = "nav2";
        nav2.Text = "Bài 2 — Phương trình bậc 2";
        nav2.Location = new Point(20, 288);
        nav2.Size = new Size(360, 46);
        nav2.BackColor = Color.White;
        nav2.FlatStyle = FlatStyle.Flat;
        nav2.TextAlign = ContentAlignment.MiddleLeft;
        nav2.Click += nav2_Click;
        nav4.Name = "nav4";
        nav4.Text = "Bài 4 — Tính tuổi";
        nav4.Location = new Point(20, 344);
        nav4.Size = new Size(360, 46);
        nav4.BackColor = Color.White;
        nav4.FlatStyle = FlatStyle.Flat;
        nav4.TextAlign = ContentAlignment.MiddleLeft;
        nav4.Click += nav4_Click;
        nav3.Name = "nav3";
        nav3.Text = "Bài 3 — Thông tin đầu sách";
        nav3.Location = new Point(20, 462);
        nav3.Size = new Size(360, 46);
        nav3.BackColor = Color.White;
        nav3.FlatStyle = FlatStyle.Flat;
        nav3.TextAlign = ContentAlignment.MiddleLeft;
        nav3.Click += nav3_Click;
        nav5.Name = "nav5";
        nav5.Text = "Bài 5 — Quản lý thư viện";
        nav5.Location = new Point(20, 518);
        nav5.Size = new Size(360, 46);
        nav5.BackColor = Color.White;
        nav5.FlatStyle = FlatStyle.Flat;
        nav5.TextAlign = ContentAlignment.MiddleLeft;
        nav5.Click += nav5_Click;
        nav6.Name = "nav6";
        nav6.Text = "Bài 6 — Trigger thư viện";
        nav6.Location = new Point(20, 574);
        nav6.Size = new Size(360, 46);
        nav6.BackColor = Color.White;
        nav6.FlatStyle = FlatStyle.Flat;
        nav6.TextAlign = ContentAlignment.MiddleLeft;
        nav6.Click += nav6_Click;
        nav7.Name = "nav7";
        nav7.Text = "Bài 7 — Tính toán dữ liệu";
        nav7.Location = new Point(20, 692);
        nav7.Size = new Size(360, 46);
        nav7.BackColor = Color.White;
        nav7.FlatStyle = FlatStyle.Flat;
        nav7.TextAlign = ContentAlignment.MiddleLeft;
        nav7.Click += nav7_Click;
        nav8.Name = "nav8";
        nav8.Text = "Bài 8 — Thống kê tổng hợp";
        nav8.Location = new Point(20, 748);
        nav8.Size = new Size(360, 46);
        nav8.BackColor = Color.White;
        nav8.FlatStyle = FlatStyle.Flat;
        nav8.TextAlign = ContentAlignment.MiddleLeft;
        nav8.Click += nav8_Click;
        menuPanel.Controls.AddRange(new Control[] { menuTitle, connectionHeading, mathHeading, libraryHeading, projectHeading, navConnection, nav1, nav2, nav4, nav3, nav5, nav6, nav7, nav8 });

        serverLabel.Name = "serverLabel";
        serverLabel.Text = "SQL Server:";
        serverLabel.Location = new Point(30, 38);
        serverLabel.Size = new Size(140, 32);
        serverLabel.TextAlign = ContentAlignment.MiddleLeft;
        serverText.Name = "serverText";
        serverText.Location = new Point(180, 40);
        serverText.Size = new Size(340, 28);
        serverText.Text = "(localdb)\\MSSQLLocalDB";
        testConnection.Name = "testConnection";
        testConnection.Text = "Kiểm tra kết nối";
        testConnection.Location = new Point(540, 35);
        testConnection.Size = new Size(220, 42);
        testConnection.FlatStyle = FlatStyle.Flat;
        testConnection.Click += testConnection_Click;
        connectionStatus.Name = "connectionStatus";
        connectionStatus.Text = "Trạng thái: Chưa kiểm tra kết nối SQL Server";
        connectionStatus.Location = new Point(30, 112);
        connectionStatus.AutoSize = true;

        calculationCard.Name = "calculationCard";
        calculationCard.Location = new Point(30, 190);
        calculationCard.Size = new Size(736, 170);
        calculationCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        calculationCard.BorderStyle = BorderStyle.FixedSingle;
        calculationCard.BackColor = Color.FromArgb(249, 250, 252);
        calculationTitle.Name = "calculationTitle";
        calculationTitle.Text = "1. CSDL Tính toán (tinhtoan.sql) — cuoiky_tinhtoan";
        calculationTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        calculationTitle.ForeColor = Color.FromArgb(29, 63, 111);
        calculationTitle.Location = new Point(18, 16);
        calculationTitle.AutoSize = true;
        calculationDescription.Name = "calculationDescription";
        calculationDescription.Text = "Bài 1, Bài 2, Bài 4";
        calculationDescription.Location = new Point(18, 59);
        calculationDescription.AutoSize = true;
        calculationStatus.Name = "calculationStatus";
        calculationStatus.Text = "Trạng thái: Chưa nạp";
        calculationStatus.Location = new Point(18, 105);
        calculationStatus.AutoSize = true;
        calculationButton.Name = "calculationButton";
        calculationButton.Text = "Kết nối & Nạp CSDL";
        calculationButton.Location = new Point(500, 105);
        calculationButton.Size = new Size(210, 46);
        calculationButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        calculationButton.FlatStyle = FlatStyle.Flat;
        calculationButton.Click += loadCalculation_Click;
        calculationCard.Controls.AddRange(new Control[] { calculationTitle, calculationDescription, calculationStatus, calculationButton });

        libraryCard.Name = "libraryCard";
        libraryCard.Location = new Point(30, 385);
        libraryCard.Size = new Size(736, 170);
        libraryCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        libraryCard.BorderStyle = BorderStyle.FixedSingle;
        libraryCard.BackColor = Color.FromArgb(249, 250, 252);
        libraryTitle.Name = "libraryTitle";
        libraryTitle.Text = "2. CSDL Thư viện (01_ThuVien.sql) — cuoiky_thuvien";
        libraryTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        libraryTitle.ForeColor = Color.FromArgb(29, 63, 111);
        libraryTitle.Location = new Point(18, 16);
        libraryTitle.AutoSize = true;
        libraryDescription.Name = "libraryDescription";
        libraryDescription.Text = "Bài 3, Bài 5, Bài 6";
        libraryDescription.Location = new Point(18, 59);
        libraryDescription.AutoSize = true;
        libraryStatus.Name = "libraryStatus";
        libraryStatus.Text = "Trạng thái: Chưa nạp";
        libraryStatus.Location = new Point(18, 105);
        libraryStatus.AutoSize = true;
        libraryButton.Name = "libraryButton";
        libraryButton.Text = "Kết nối & Nạp CSDL";
        libraryButton.Location = new Point(500, 105);
        libraryButton.Size = new Size(210, 46);
        libraryButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        libraryButton.FlatStyle = FlatStyle.Flat;
        libraryButton.Click += loadLibrary_Click;
        libraryCard.Controls.AddRange(new Control[] { libraryTitle, libraryDescription, libraryStatus, libraryButton });

        projectCard.Name = "projectCard";
        projectCard.Location = new Point(30, 580);
        projectCard.Size = new Size(736, 170);
        projectCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        projectCard.BorderStyle = BorderStyle.FixedSingle;
        projectCard.BackColor = Color.FromArgb(249, 250, 252);
        projectTitle.Name = "projectTitle";
        projectTitle.Text = "3. CSDL Đề án (02_DeAn.sql) — cuoiky_dean";
        projectTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        projectTitle.ForeColor = Color.FromArgb(29, 63, 111);
        projectTitle.Location = new Point(18, 16);
        projectTitle.AutoSize = true;
        projectDescription.Name = "projectDescription";
        projectDescription.Text = "Bài 7, Bài 8";
        projectDescription.Location = new Point(18, 59);
        projectDescription.AutoSize = true;
        projectStatus.Name = "projectStatus";
        projectStatus.Text = "Trạng thái: Chưa nạp";
        projectStatus.Location = new Point(18, 105);
        projectStatus.AutoSize = true;
        projectButton.Name = "projectButton";
        projectButton.Text = "Kết nối & Nạp CSDL";
        projectButton.Location = new Point(500, 105);
        projectButton.Size = new Size(210, 46);
        projectButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        projectButton.FlatStyle = FlatStyle.Flat;
        projectButton.Click += loadProject_Click;
        projectCard.Controls.AddRange(new Control[] { projectTitle, projectDescription, projectStatus, projectButton });

        connectionView.Controls.AddRange(new Control[] { serverLabel, serverText, testConnection, connectionStatus, calculationCard, libraryCard, projectCard });
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1200, 760);
        MinimumSize = new Size(1160, 650);
        Font = new Font("Segoe UI", 9F);
        Name = "MainForm";
        Text = "Bài tập lớn SQL DBMS";
        StartPosition = FormStartPosition.CenterScreen;
        WindowState = FormWindowState.Maximized;
        Controls.Add(mainSplit);
        mainSplit.Panel1.ResumeLayout(false);
        mainSplit.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)mainSplit).EndInit();
        mainSplit.ResumeLayout(false);
        menuPanel.ResumeLayout(false);
        contentPanel.ResumeLayout(false);
        connectionView.ResumeLayout(false);
        ResumeLayout(false);
    }
}
